// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoThzceVOeGOPlJR_jCs4dgZr2Y5hOaK4',
    appId: '1:820672190951:web:e73241f16cdb35bfe90542',
    messagingSenderId: '820672190951',
    projectId: 'latihanuts-f7fd4',
    authDomain: 'latihanuts-f7fd4.firebaseapp.com',
    databaseURL: 'https://latihanuts-f7fd4-default-rtdb.firebaseio.com',
    storageBucket: 'latihanuts-f7fd4.firebasestorage.app',
    measurementId: 'G-QGYG2SZMCD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8J0-UTnNRWowV5Z5-j4oz6fDIJOrfHZI',
    appId: '1:820672190951:android:f7541bd2bed97a9de90542',
    messagingSenderId: '820672190951',
    projectId: 'latihanuts-f7fd4',
    databaseURL: 'https://latihanuts-f7fd4-default-rtdb.firebaseio.com',
    storageBucket: 'latihanuts-f7fd4.firebasestorage.app',
  );
}
