// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjhvZApdIVG5HNsZenw6DXGuT13u-f0cU',
    appId: '1:908437983135:web:1bd876f77c84d562cc37aa',
    messagingSenderId: '908437983135',
    projectId: 'first-app-69ed1',
    authDomain: 'first-app-69ed1.firebaseapp.com',
    databaseURL: 'https://first-app-69ed1-default-rtdb.firebaseio.com',
    storageBucket: 'first-app-69ed1.firebasestorage.app',
    measurementId: 'G-JZ0Q8P5PXR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPg5VyK0vk3Xokx74iVw6c6Pzx_ij7plk',
    appId: '1:908437983135:android:dbb0c09fbc3b2f52cc37aa',
    messagingSenderId: '908437983135',
    projectId: 'first-app-69ed1',
    databaseURL: 'https://first-app-69ed1-default-rtdb.firebaseio.com',
    storageBucket: 'first-app-69ed1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtEBh9JC4DtyYnNX5IqrJEl6Z3uLP7q64',
    appId: '1:908437983135:ios:568751f9d72c2f08cc37aa',
    messagingSenderId: '908437983135',
    projectId: 'first-app-69ed1',
    databaseURL: 'https://first-app-69ed1-default-rtdb.firebaseio.com',
    storageBucket: 'first-app-69ed1.firebasestorage.app',
    iosBundleId: 'com.example.cepuApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtEBh9JC4DtyYnNX5IqrJEl6Z3uLP7q64',
    appId: '1:908437983135:ios:568751f9d72c2f08cc37aa',
    messagingSenderId: '908437983135',
    projectId: 'first-app-69ed1',
    databaseURL: 'https://first-app-69ed1-default-rtdb.firebaseio.com',
    storageBucket: 'first-app-69ed1.firebasestorage.app',
    iosBundleId: 'com.example.cepuApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjhvZApdIVG5HNsZenw6DXGuT13u-f0cU',
    appId: '1:908437983135:web:4a05d4737c93f71fcc37aa',
    messagingSenderId: '908437983135',
    projectId: 'first-app-69ed1',
    authDomain: 'first-app-69ed1.firebaseapp.com',
    databaseURL: 'https://first-app-69ed1-default-rtdb.firebaseio.com',
    storageBucket: 'first-app-69ed1.firebasestorage.app',
    measurementId: 'G-Y7GVYZDRL8',
  );

}