// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjhvZApdIVG5HNsZenw6DXGuT13u-f0cU',
    appId: '1:908437983135:web:1bd876f77c84d562cc37aa',
    messagingSenderId: '908437983135',
    projectId: 'first-app-69ed1',
    authDomain: 'first-app-69ed1.firebaseapp.com',
    databaseURL: 'https://console.firebase.google.com/project/first-app-69ed1/database/first-app-69ed1-default-rtdb/data.firebaseio.com',
    storageBucket: 'first-app-69ed1.firebasestorage.app',
    measurementId: 'G-JZ0Q8P5PXR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPg5VyK0vk3Xokx74iVw6c6Pzx_ij7plk',
    appId: '1:908437983135:android:5e384cba3e52fc7ecc37aa',
    messagingSenderId: '908437983135',
    projectId: 'first-app-69ed1',
    databaseURL: 'https://console.firebase.google.com/project/first-app-69ed1/database/first-app-69ed1-default-rtdb/data.firebaseio.com',
    storageBucket: 'first-app-69ed1.firebasestorage.app',
  );

}